name: test-task
recipe: laravel
config:
  via: apache
  php: '8.1'
  database: mariadb:10.6
  webroot: public
services:
  appserver:
    build_as_root:
      - a2enmod headers
    build:
      - "composer --ansi install"